# Generated by Django 5.0.1 on 2024-01-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_face_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
